language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn test
deploy:
  provider: npm
  email: joel@oblador.se
  api_key:
    secure: "qZAQyK4L+XZjzJIkqCpBk49EzwatWVOQQli3K9Giuu+XRIY/j5gPqUaVwbn+JmeCAKqNoWPmravFNcv4akqY6iT7ZtM7CCAwDrpY7nNAuomz6MR+1y0Be8ValFhcl6nM4A19j4GFA90cV2d49tQKDzSut494h/Et2UjwPGn9OJEQPYZjO8FW16iXlpDYbLqi558uuR/wbZD9Oh5dgfk02bUA/rw8YyXG5jizyLBwEUKi28nWgeAcR9JpYfmLfN+CiApj3bUW59tEnJV3tohOXbs1dnvB5X5tRINzR2bwTgDtKxcb41avxXJx19OHAsMg5VH9LvJsExWIwZvdAYYHOJDbaGcLnETedf5WprTbbg5PRGOCC3pObIc6iTtx0OfZ1FGzesm6nLJQH2qsOCsT43KC4Yo7quWViTVUUbX6W1IKXb5zIaccNxsjqo8PDYAzIOTMTZYp7LgD0hSy3JyzEB6+XRf6CVcajZ0gqtjQTiyBdtv+ZX+7OAMr8SzEUls/B17OkqPEaL2cnjFd4Q36qeS0qCU7LNWxrNlPQa79R8m4VX6LBuDJbiumkXWg+SlsSnNm0wQCniT4yMDxv0/iUGYricSe/V3xPEJBoVdEaWmlaIeUalXUjOjji7/isGoYufMggdmXYvDg6Q/Uwx1ooQPR/rU9NYjvXf5rYnv9/Vw="
  on:
    tags: true
    repo: oblador/react-native-image-progress
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
